language: node_js
node_js:
- 9
cache:
  directories:
  - node_modules
env:
  global:
  - ENCRYPTION_LABEL: fd64aa3f06ec
  - secure: uayU4oNG1e8Ie2ri982BtzchgYz4bzNvdPA8tckPxshITWuDWDmJUfqzSqReF96BXEbK9xSZiBoKO4p3xcPmwttYiE1iFy9+3PgTPtdgyJChcBSd0C5xseTQ8PU+XSqSXeEWRWEIrVeuhhpqOTMUamc3kGReCbdk+Ia6MhYZZX+OFhc/UvBS493UEcXzoSRg9uXTFw2gRrw1OKIBL874ORkU3p3gCGfPTYZdZau5TXYz3w65bwidq1SkKksCNxpgDUPt2SxTZNSPVjiGD53fRa/UZP/gkcVmQUsCYmJKydZHqoHKiDKecLRSnjahpzg06vOCy63D98nCdEqLLTfUMKJvGMsbmHjpk/No8rrqeZ57VTELi6qKqhmotj4ctac2Lq/aPKhHaGBEH+iIGxgCrqeb60/XQ0ulmDmWpiU9RSSWw29I4ZQ9gikr0NQ2Hw+xvy5Y41Z6XZiu7yPUZV14Xem5ei0PnP8xa5pOzGqG540cVnsTx+9/+enjhW61cDEbcEH+DOVP38gI4wecBWDucLKumfmxKUfnT7ipALbJ4i82b16Zdh7bts8dLXhoycZ+L8RlY37/0xzjYu+wR4MzC6tX2nI0QKQsixHSmLfHyQDQUWU12i+Q4BHFOS3aO8hpkBEzZZA2qIaUDjsMw8rbDShXt3WAIOEhtRh5w730gqA=
before_install:
- scripts/ci-prepare
jobs:
  include:
  - stage: scrape
    if: branch = master AND type IN (cron)
    script:
    - npm run scrape && npm run deploy:gh-scraped
  - stage: test
    if: NOT branch = master AND type IN (push, pull_request)
    script:
    - npm test
  - stage: web
    if: branch = master AND type IN (push)
    script:
    - npm test && npm run fetch:gh-scraped && npm run export && npm run deploy:gh-pages
