#!/bin/bash -e

# setup ssh-agent and provide the GitHub deploy key
#eval "$(ssh-agent -s)"
#chmod 600 ~/.ssh/push_key
#ssh-add ~/.ssh/push_key
#echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config




# Get the deploy key by using Travis's stored variables to decrypt deploy_key.enc
ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
openssl aes-256-cbc -K ${ENCRYPTED_KEY} -iv ${ENCRYPTED_IV} -in deploy_key.enc -out deploy_key -d
chmod 600 deploy_key
eval `ssh-agent -s`
ssh-add deploy_key

# Permanently add deploy key to ssh config
KEY_PATH=$(cd "$(dirname "deploy_key")"; pwd)/$(basename "deploy_key")
echo -e "Host github.com\n\tStrictHostKeyChecking no\n\tIdentityFile ${KEY_PATH}\n" >> ~/.ssh/config

# configure git
git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"
