#!/bin/bash -eu

SOURCE_BRANCH=${1}

TARGET_FOLDER=${2}

REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}

SHA=`git rev-parse --verify HEAD`

if [ -d "${TARGET_FOLDER}" ]; then
    echo "Folder already exists '${TARGET_FOLDER}'"
    exit 1
fi

mkdir -p ${TARGET_FOLDER}

TARGET_FOLDER=$(cd "$(dirname "${TARGET_FOLDER}")"; pwd)/$(basename "${TARGET_FOLDER}")

echo "Fetching '${SOURCE_BRANCH}' to folder '${TARGET_FOLDER}'"

git clone ${REPO} ${TARGET_FOLDER}
cd ${TARGET_FOLDER}
git checkout ${SOURCE_BRANCH}

git pull

rm -rf .git
