#!/bin/bash -eu

SOURCE_FOLDER=$(cd "$(dirname "${1}")"; pwd)/$(basename "${1}")

TARGET_FOLDER=${2}

SOURCE_BRANCH="master"
TARGET_BRANCH=${3}

REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}

SHA=`git rev-parse --verify HEAD`

if [ ! -d "${SOURCE_FOLDER}" ]; then
    echo "Can't find folder '${SOURCE_FOLDER}'"
    exit 1
fi

TMP_FOLDER="tmp/deploy/`basename ${TARGET_BRANCH}`"
rm -rf ${TMP_FOLDER}
mkdir -p ${TMP_FOLDER}
TMP_FOLDER=$(cd "$(dirname "${TMP_FOLDER}")"; pwd)/$(basename "${TMP_FOLDER}")

echo "Updating branch '${TARGET_BRANCH}' with folder '${SOURCE_FOLDER}'"

# Clone the existing branch for this repo into temporary folder
# Create a new empty branch if branch doesn't exist yet (should only happen on first deploy)
git clone ${REPO} ${TMP_FOLDER}

cd ${TMP_FOLDER}
git checkout ${TARGET_BRANCH} || git checkout --orphan ${TARGET_BRANCH}

# Grab the new content
rsync -a ${SOURCE_FOLDER}/ ${TMP_FOLDER}/${TARGET_FOLDER}/

# Push changes
if [ -n "$(git status --porcelain)" ]; then
    git add --all .
    git commit --message "Deploy to ${TARGET_BRANCH}: ${SHA}"
    git push ${SSH_REPO} ${TARGET_BRANCH}
    echo "${TARGET_BRANCH} deployed"
else
    echo "No changes for ${TARGET_BRANCH}; exiting"
    exit 0
fi
